services:
  app:
    image: ghcr.io/richardsolomou/printhub:latest
    build:
      context: .
      args:
        VITE_CONVEX_URL: ${VITE_CONVEX_URL}
        VITE_POSTHOG_PROJECT_TOKEN: ${VITE_POSTHOG_PROJECT_TOKEN}
        VITE_POSTHOG_HOST: ${VITE_POSTHOG_HOST}
    restart: unless-stopped
    ports:
      - '3010:3000'
    environment:
      CONVEX_ACTION_SECRET: ${CONVEX_ACTION_SECRET}
      ADMIN_EMAILS: ${ADMIN_EMAILS}
    volumes:
      - ${PRINTS_HOST_DIR}:/prints
