allowBuilds:
  argon2: true
  better-sqlite3: true
  core-js: true
  esbuild: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@tanstack/react-virtual@3.14.6'
  - '@tanstack/virtual-core@3.17.4'
  - es-module-lexer@2.3.1
  - nanoid@3.3.16
