allowBuilds:
  argon2: true
  better-sqlite3: true
  core-js: true
  esbuild: true
  sharp: false
  workerd: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@tanstack/react-virtual@3.14.6'
  - '@tanstack/virtual-core@3.17.4'
  - es-module-lexer@2.3.1
  - fast-uri@3.1.4
  - fast-xml-parser@5.10.1
  - nanoid@3.3.16

overrides:
  fast-uri: 3.1.4
  fast-xml-parser: 5.10.1
  sharp: 0.35.3
