import fs from 'node:fs/promises'
import path from 'node:path'
import { expect, test } from '@playwright/test'
import { strFromU8, unzipSync } from 'fflate'

const email = 'owner@example.com'
const password = 'correct-horse-battery-staple'

test('admin setup, upload, viewer, settings, invite, and sign out', async ({ page, browser }) => {
  test.setTimeout(120_000)
  await page.goto('/')
  await expect.poll(() => page.locator('html').evaluate((element) => getComputedStyle(element).fontSize)).toBe('18px')
  await expect(page.getByRole('heading', { name: 'Private resin production, not a generic printer dashboard' })).toBeVisible()
  await expect(page.getByText('it is not designed for FDM production')).toBeVisible()
  await page.getByRole('button', { name: 'Set up PrintHub' }).click()
  await expect(page.locator('form[data-hydrated="true"]')).toBeVisible()
  await page.getByLabel('Name').fill('Owner')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password').fill(password)
  await page.getByLabel('Password').blur()
  await expect(page.getByLabel('Password')).toHaveValue(password)
  await page.getByLabel('Password').press('Enter')
  await expect(page.getByRole('heading', { name: 'Choose storage' })).toBeVisible()
  await page.getByRole('button', { name: 'Finish setup' }).click()
  await expect(page.getByRole('heading', { name: 'Add your resin printers' })).toBeVisible()
  await page.getByLabel('Name').fill('Printer 1')
  await page.getByLabel('Width').fill('129')
  await page.getByLabel('Depth').fill('80')
  await page.getByLabel('Height').fill('150')
  await page.getByRole('button', { name: 'Add resin printer' }).click()
  await page.getByRole('button', { name: 'Finish setup' }).click()
  await expect(page.getByRole('button', { name: 'Add a print' })).toBeVisible()

  await page.getByRole('button', { name: 'Add a print' }).click()
  await page.locator('input[type=file]').setInputFiles(path.join(import.meta.dirname, 'fixtures/triangle.stl'))
  await expect(page.getByLabel('Name')).toHaveValue('triangle')
  await page.getByRole('button', { name: 'Add 1 print' }).click()
  await expect(page.getByText('triangle', { exact: true })).toBeVisible()
  await expect(page.locator('[data-status="todo"] .virtual-list')).toBeVisible()
  await expect(page.locator('[data-status="todo"] .virtual-row')).toHaveCount(1)
  await expect(page.locator('[data-status="todo"] .column-body')).toHaveAttribute('data-auto-scrollable')
  await page.locator('main.board').evaluate((element) => element.setAttribute('data-retained-probe', 'true'))
  await page.getByPlaceholder('Search prints…').fill('not-the-print')
  await expect(page.getByText('triangle', { exact: true })).not.toBeVisible()
  await expect(page.locator('main.board')).toHaveAttribute('data-retained-probe', 'true')
  await expect(page).toHaveURL(/q=not-the-print/)
  await page.reload()
  await expect(page.getByRole('region', { name: 'Board filters' })).toHaveAttribute('data-hydrated', 'true')
  await expect(page.getByPlaceholder('Search prints…')).toHaveValue('not-the-print')
  await page.getByRole('button', { name: 'Clear search' }).click()
  await expect(page.getByPlaceholder('Search prints…')).toHaveValue('')
  await expect(page).not.toHaveURL(/q=/)
  await expect(page.getByText('triangle', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^Filters/ }).click()
  await expect
    .poll(async () => {
      const [dateBackground, inputBackground] = await Promise.all([
        page
          .locator('[data-slot="date-picker-trigger"]')
          .first()
          .evaluate((element) => getComputedStyle(element).backgroundColor),
        page.getByLabel('Minimum quantity').evaluate((element) => getComputedStyle(element).backgroundColor),
      ])
      return dateBackground === inputBackground
    })
    .toBe(true)
  await page.getByLabel('Notes availability').click()
  await page.getByRole('option', { name: 'Missing' }).click()
  await expect(page.getByRole('button', { name: /Missing notes/ })).toBeVisible()
  await page.getByRole('button', { name: /Missing notes/ }).click()
  await expect(page.getByRole('button', { name: 'Close filters' })).not.toBeVisible()
  await expect.poll(() => page.locator('body').evaluate((element) => getComputedStyle(element).pointerEvents)).toBe('auto')
  expect(
    await page.locator('[data-status="todo"] .virtual-row').evaluate((element) => getComputedStyle(element).transitionDuration),
  ).not.toBe('0s')

  await page.getByRole('button', { name: 'Add a print' }).click()
  await page.locator('input[type=file]').setInputFiles(path.join(import.meta.dirname, 'fixtures/oversized.stl'))
  await page.getByRole('button', { name: 'Add 1 print' }).click()
  await expect(page.getByText('oversized', { exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'Planner' }).click()
  const plannerFilters = page.getByRole('region', { name: 'Planner filters' })
  await expect(plannerFilters).toHaveAttribute('data-hydrated', 'true')
  await expect(plannerFilters.getByLabel('Sort requests')).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'Model orientation' })).not.toBeVisible()
  await expect(page.getByText('1 queued model does not fit any configured printer')).toBeVisible({ timeout: 30_000 })
  const exportButton = page.getByRole('button', { name: 'Export 3MF' })
  await expect(exportButton).toBeVisible({ timeout: 30_000 })
  await plannerFilters.getByPlaceholder('Search prints…').fill('not-a-model')
  await expect(exportButton).not.toBeVisible()
  await expect(page.getByText('No queued models match these filters.')).toBeVisible()
  await plannerFilters.getByRole('button', { name: 'Clear search' }).click()
  await expect(exportButton).toBeVisible({ timeout: 30_000 })
  await plannerFilters.getByRole('button', { name: /^Filters/ }).click()
  await page.getByPlaceholder('Anyone').click()
  await page.getByRole('option', { name: /Owner/ }).click()
  await page.getByRole('button', { name: 'Done' }).click()
  await expect(page).toHaveURL(/requester=Owner/)
  await page.getByLabel('Profile').click()
  await page.getByRole('option', { name: 'Printer 1', exact: true }).click()
  await expect(exportButton).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await exportButton.click()
  const plateDownload = await downloadPromise
  expect(plateDownload.suggestedFilename()).toBe('printer-1-plate-1.3mf')
  const platePath = await plateDownload.path()
  expect(platePath).not.toBeNull()
  const archive = unzipSync(await fs.readFile(platePath))
  expect(Object.keys(archive).sort()).toEqual(['3D/3dmodel.model', '[Content_Types].xml', '_rels/.rels'])
  expect(strFromU8(archive['3D/3dmodel.model'])).toContain('name="triangle"')
  await expect(exportButton).toBeVisible()
  await page.getByRole('link', { name: 'Board', exact: true }).click()

  const card = page.locator('[data-status="todo"] .card').filter({ hasText: 'triangle' })
  const target = page.locator('[data-status="in_progress"] .column-body')
  const [cardBox, targetBox] = await Promise.all([card.boundingBox(), target.boundingBox()])
  expect(cardBox).not.toBeNull()
  expect(targetBox).not.toBeNull()
  await page.mouse.move(cardBox!.x + 32, cardBox!.y + 32)
  await page.mouse.down()
  await page.mouse.move(targetBox!.x + targetBox!.width / 2, targetBox!.y + 40, { steps: 12 })
  await page.mouse.up()
  await expect(page.locator('[data-status="in_progress"] .card')).toContainText('triangle')
  await page.getByLabel('Sort requests').click()
  await page.getByRole('option', { name: 'Recently updated', exact: true }).click()
  await expect(page.locator('[data-status="in_progress"] .card')).toHaveAttribute('data-draggable', 'false')
  await page.getByLabel('Sort requests').click()
  await page.getByRole('option', { name: 'Board order' }).click()
  await expect(page.locator('[data-status="in_progress"] .card')).toHaveAttribute('data-draggable', 'true')

  const thumbnail = page.locator('[data-status="in_progress"] img[src^="/api/thumbs/"]')
  await expect(thumbnail).toBeVisible({ timeout: 30_000 })
  const thumbnailResponse = await page.request.get((await thumbnail.getAttribute('src')) as string)
  expect(thumbnailResponse.ok()).toBeTruthy()

  await page.getByText('triangle', { exact: true }).click()
  await expect(page.getByRole('button', { name: 'Add note' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Add link' })).toBeVisible()
  const download = page.getByRole('link', { name: 'Download STL' })
  const fileResponse = await page.request.get((await download.getAttribute('href')) as string)
  expect(fileResponse.ok()).toBeTruthy()
  expect(fileResponse.headers()['content-type']).toContain('model/stl')
  await expect(page.locator('.viewer canvas')).toBeVisible({ timeout: 15_000 })
  await page.getByRole('button', { name: 'Close' }).click()

  await page.getByRole('link', { name: 'Settings' }).click()
  await expect(page).toHaveURL(/\/settings\/account$/)
  await expect(page.locator('header').getByText(/^v\d/)).toHaveCount(0)
  await expect(page.locator('[data-slot="settings-page"]')).toBeVisible()
  await expect(page.locator('[data-slot="settings-header"]')).toContainText('Account')
  await expect(page.locator('[data-slot="settings-section"]')).toHaveCount(2)
  await expect(page.getByRole('heading', { name: 'Sign-in methods' })).toBeVisible()
  await expect(page.locator('[data-auth-method="password"]')).toContainText('Linked')
  await expect(page.getByLabel('Current password')).toHaveCount(0)
  await page.getByRole('button', { name: 'Change password' }).click()
  await expect(page.getByRole('heading', { name: 'Change password' })).toBeVisible()
  await expect(page.getByLabel('Current password')).toBeVisible()
  await page.getByRole('button', { name: 'Close' }).click()
  await expect(page.getByLabel('Current password')).toHaveCount(0)
  await expect(page.locator('[data-auth-method="google"]')).toHaveCount(0)
  await expect(page.locator('[data-auth-method="discord"]')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('header[data-hydrated]')).toHaveAttribute('data-hydrated', 'true')
  await page.evaluate(() => ((window as Window & { spaNavigationProbe?: boolean }).spaNavigationProbe = true))
  await page.getByRole('link', { name: 'Go to board' }).click()
  await expect(page.getByRole('button', { name: 'Add a print' })).toBeVisible({ timeout: 2_000 })
  await expect.poll(() => page.evaluate(() => (window as Window & { spaNavigationProbe?: boolean }).spaNavigationProbe)).toBe(true)
  await page.getByRole('button', { name: 'Add a print' }).click()
  await page.getByLabel('For').fill('does-not-exist')
  await expect(page.getByText('No people found.')).toBeVisible()
  await expect(page.getByRole('option', { name: 'Owner' })).not.toBeVisible()
  await page.getByLabel('For').press('Escape')
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(page.getByRole('heading', { name: 'Add prints' })).not.toBeVisible()
  await page.getByRole('link', { name: 'Settings' }).click()
  await page.getByRole('link', { name: 'Diagnostics' }).click()
  await expect(page.getByText(/integrity ok/)).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.getByRole('link', { name: 'Users' }).click()
  await expect(page.getByText('Admin', { exact: true })).toBeVisible()
  await page.getByLabel('Search users').fill('missing-user')
  await expect(page.getByText('No users match these filters.')).toBeVisible()
  await page.getByLabel('Search users').fill('')
  await page.getByLabel('Filter users by role').click()
  await page.getByRole('option', { name: 'Requester', exact: true }).click()
  await expect(page.getByText('No users match these filters.')).toBeVisible()
  await page.getByLabel('Filter users by role').click()
  await page.getByRole('option', { name: 'All roles', exact: true }).click()
  await expect(page.getByText('1 user', { exact: true })).toBeVisible()
  await expect(page.getByLabel('Users per page')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Set password' })).not.toBeVisible()
  await page.getByLabel('View Owner').click()
  await expect(page.getByRole('heading', { name: 'User details' })).toBeVisible()
  await page.getByRole('button', { name: 'Done' }).click()
  await page.getByRole('button', { name: 'Add user' }).click()
  await expect(page.getByRole('heading', { name: 'Create user' })).toBeVisible()
  await page.getByRole('button', { name: 'Cancel' }).click()
  await page.getByRole('button', { name: 'Invite user' }).click()
  await expect(page.getByRole('heading', { name: 'Create invite link' })).toBeVisible()
  await page.getByLabel('Who is this for?').fill('Requester')
  await page.getByRole('button', { name: 'Create invite link' }).click()
  const inviteUrl = await page.locator('#invite-link').inputValue()
  await page.getByRole('button', { name: 'Done' }).click()

  const inviteContext = await browser.newContext()
  const invitePage = await inviteContext.newPage()
  await invitePage.goto(inviteUrl)
  await expect(invitePage.getByRole('heading', { name: "You're invited" })).toBeVisible()
  await expect(invitePage.locator('form[data-hydrated="true"]')).toBeVisible()
  await invitePage.getByLabel('Name').fill('Requester')
  await invitePage.getByLabel('Email').fill('requester@example.com')
  await invitePage.getByLabel('Password').fill(password)
  await invitePage.getByLabel('Password').blur()
  await invitePage.getByLabel('Password').press('Enter')
  await expect(invitePage.getByRole('button', { name: 'Add a print' })).toBeVisible()
  await invitePage.getByRole('link', { name: 'Settings' }).click()
  await expect(invitePage).toHaveURL(/\/settings\/account$/)
  await expect(invitePage.getByRole('navigation', { name: 'Settings sections' }).getByRole('link')).toHaveCount(1)
  await expect(invitePage.getByRole('link', { name: 'Account', exact: true })).toBeVisible()
  await invitePage.goto('/settings/users')
  await expect(invitePage).toHaveURL(/\/settings\/account$/)
  await expect(invitePage.getByRole('heading', { name: 'Account' })).toBeVisible()
  await inviteContext.close()

  await expect(page.getByLabel('View Requester')).toBeVisible()
  await page.getByLabel('View Requester').click()
  await page.getByLabel('Role for Requester').click()
  await page.getByRole('option', { name: 'Admin', exact: true }).click()
  await page.getByRole('button', { name: 'Save role' }).click()
  await expect(page.getByText('Requester is now an admin.')).toBeVisible()

  await page.getByRole('link', { name: 'Integrations' }).click()
  await expect(page.getByRole('heading', { name: 'Integrations' })).toBeVisible()
  await expect(page.getByText('Built-in email and password authentication.')).toBeVisible()
  const smtpCard = page.getByRole('heading', { name: 'SMTP' }).locator('../..')
  await expect(smtpCard).toContainText('Not configured')
  await expect(smtpCard.getByRole('button', { name: 'Configure' })).toBeVisible()
  await expect(page.getByText('Account creation always requires an invite.')).toBeVisible()

  const sseConnected = await page.evaluate(async () => {
    const controller = new AbortController()
    const response = await fetch('/api/events', { signal: controller.signal })
    const first = await response.body?.getReader().read()
    controller.abort()
    return response.status === 200 && new TextDecoder().decode(first?.value).includes('retry: 2000')
  })
  expect(sseConnected).toBe(true)

  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('link', { name: 'Board', exact: true }).click()
  await page.reload()
  await expect(page).toHaveURL(/\/settings\/board$/)
  await expect(page.getByLabel('Request visibility')).toBeVisible()
  await page.getByLabel('Request visibility').click()
  await page.getByRole('option', { name: /Private/ }).click()
  await expect(page.getByText('Board settings saved.')).toBeVisible()

  await page.getByRole('link', { name: 'Printers' }).click()
  await page.getByLabel('Name').fill('Custom workshop printer')
  await page.getByLabel('Width').fill('300')
  await page.getByLabel('Depth').fill('200')
  await page.getByLabel('Height').fill('250')
  await page.getByRole('button', { name: 'Add resin printer' }).click()
  await expect(page.getByText('Resin printers updated.')).toBeVisible()
  await expect(page.getByText('Custom workshop printer', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Remove Custom workshop printer' }).click()
  await expect(page.getByText('Custom workshop printer', { exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Remove Printer 1' }).click()
  await expect(page.getByText('Printer list cleared. Planner is hidden.')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Planner' })).not.toBeVisible()
  await page.goto('/planner')
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('button', { name: 'Add a print' })).toBeVisible()
  await page.getByRole('link', { name: 'Settings' }).click()
  await page.getByRole('link', { name: 'Account' }).click()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByRole('button', { name: 'Sign in' })).toBeVisible()
})

test('health and metrics expose correlation and operational data', async ({ request }) => {
  const root = await request.get('/')
  expect(root.headers()['content-security-policy']).toContain("default-src 'self'")
  expect(root.headers()['x-content-type-options']).toBe('nosniff')
  expect(root.headers()['x-frame-options']).toBe('DENY')
  const health = await request.get('/api/health', { headers: { 'x-request-id': 'e2e-health' } })
  expect(health.ok()).toBeTruthy()
  expect(health.headers()['x-request-id']).toBe('e2e-health')
  const metrics = await request.get('/api/metrics')
  expect(metrics.ok()).toBeTruthy()
  await expect(metrics.text()).resolves.toContain('printhub_api_requests_total')

  const unauthorizedFile = await request.get('/api/files/missing')
  expect(unauthorizedFile.status()).toBe(401)

  const unauthorizedEvents = await request.get('/api/events')
  expect(unauthorizedEvents.status()).toBe(401)
})
