export const MAX_UPLOAD_BYTES = 1024 * 1024 * 1024
export const ASSET_GENERATION_MEMORY_MULTIPLIER = 4
export const ASSET_GENERATION_MEMORY_BUDGET = MAX_UPLOAD_BYTES * ASSET_GENERATION_MEMORY_MULTIPLIER
